loading:
  tensor_like: false
model:
  model_type: random
  model_args: {}
preprocessing:
  preprocessor_args:
    time_id_features:
    - f_231
    - f_250
    - f_119
    - f_265
    - f_280
    - f_270
    - f_197
    - f_65
    - f_25
    - f_155
    - f_71
    - f_15
    - f_212
    - f_179
    - f_237
    - f_297
    - f_190
    - f_76
    - f_286
    - f_137
    - f_165
    - f_255
    - f_172
    - f_58
    - f_118
    - f_93
    - f_168
    - f_243
    - f_185
    - f_92
    - f_247
    - f_232
    - f_264
    - f_225
    - f_100
    - f_106
    - f_187
    - f_21
    - f_135
    - f_42
    - f_257
    - f_41
    - f_145
    - f_246
    - f_79
    - f_146
    - f_216
    - f_80
    - f_214
    - f_83
    - f_273
    - f_52
    - f_3
    - f_31
    - f_207
    - f_150
    - f_17
    - f_169
    - f_268
    - f_233
    - f_256
    - f_226
    - f_78
    - f_113
    - f_194
    - f_90
    - f_274
    - f_85
    - f_251
    - f_16
    - f_44
    - f_153
    - f_5
    - f_277
    - f_77
    - f_109
    - f_174
    - f_96
    - f_193
    - f_206
    - f_121
    - f_116
    - f_173
    - f_210
    - f_87
  preprocessor_type: naive
validator_args:
  n_folds: 1
  n_timesteps_per_fold: 200
  n_timesteps_to_train: 600
  tensor_like: false
