loading:
  tensor_like: false
model:
  model_args:
    embedding_dim_list:
    - 8
    batch_size: 128
    learning_rate: 0.002
    mlp_params:
      activation_type: mish
      dropout_prob: 0.5
      hidden_sizes:
      - 32
    num_epochs: 1 #16
    objective: corr
    random_state: 123
    weight_decay: 1.0e-05
  model_type: mlp
preprocessing:
  preprocessor_args:
    cols_to_drop:
    - time_id
    crop_high: 4
    crop_low: -5
    scaler_features: StandardScaler
    time_id_features:
    - f_231
    - f_250
    - f_119
    - f_265
    - f_280
    - f_270
    - f_197
    - f_65
    - f_25
    - f_155
  preprocessor_type: naive
validator_args:
  n_folds: 3
  n_timesteps_per_fold: 200
  n_timesteps_to_train: 600
  tensor_like: false
